### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/lightgbm#1]
Ideas

- [x] Mirror the [Python API](https://lightgbm.readthedocs.io/en/latest/Python-API.html) (with a little Ruby flair - no `get_`/`set_` prefixes, etc)
  - [x] Early stopping
  - [x] `cv` method
- [x] Add Regressor and Classifier APIs
- [x] Vendor LightGBM for easier installation - `vendor` branch

**Comment by breim** [comment]
You are awesome <3
