### ISSUE TITLE
Gem breaks on arm64 (Apple M1)

### ISSUE THREAD

**Issue by timcraft** [ankane/lightgbm#3]
Steps to reproduce:

    $ ruby -v
    ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]

    $ brew install libomp
    Warning: libomp 11.1.0 is already installed and up-to-date.

    $ gem install lightgbm
    Successfully installed lightgbm-0.2.2
    1 gem installed

    $ irb -r lightgbm
    irb(main):001:0> x = [[1, 2], [3, 4], [5, 6], [7, 8]]
    => [[1, 2], [3, 4], [5, 6], [7, 8]]
    irb(main):002:0> y = [1, 2, 3, 4]
    => [1, 2, 3, 4]
    irb(main):003:0> train_set = LightGBM::Dataset.new(x, label: y)
    /Users/tim/.gem/ruby/3.0.0/gems/ffi-1.14.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'lib_lightgbm.dylib': dlopen(lib_lightgbm.dylib, 5): image not found. (LoadError)
    Could not open library 'lib_lightgbm.so': dlopen(lib_lightgbm.so, 5): image not found.
    Could not open library 'lib_lightgbm.so.dylib': dlopen(lib_lightgbm.so.dylib, 5): image not found.
    Could not open library '/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.2/vendor/lib_lightgbm.dylib': dlopen(/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.2/vendor/lib_lightgbm.dylib, 5): no suitable image found.  Did find:
    	/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.2/vendor/lib_lightgbm.dylib: mach-o, but wrong architecture
    	/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.2/vendor/lib_lightgbm.dylib: mach-o, but wrong architecture
    ...

GitHub Actions doesn't have support for M1 yet.

**Comment by ankane** [comment]
Hey @timcraft, I was able to cross-compile LightGBM with OpenMP for arm64 on GitHub Actions ([code](https://github.com/ankane/ml-builds/blob/lightgbm-arm-openmp/.github/workflows/lightgbm-mac-arm.yml)), but could use some help testing it.

Can you download the [build artifact](https://github.com/ankane/ml-builds/actions/runs/628014039), set the following in your code:

```ruby
LightGBM.ffi_lib = "path/to/downloaded/lib_lightgbm.dylib"
```

and try running it with and without the Homebrew `libomp` formula installed?

**Comment by timcraft** [comment]
Great, happy to help test. This is what I get:

    /Users/tim/.gem/ruby/3.0.0/gems/ffi-1.14.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/tim/Downloads/lib_lightgbm.dylib': dlopen(/Users/tim/Downloads/lib_lightgbm.dylib, 5): Library not loaded: @@HOMEBREW_PREFIX@@/opt/libomp/lib/libomp.dylib (LoadError)
      Referenced from: /Users/tim/Downloads/lib_lightgbm.dylib
      Reason: image not found

It's the same output with and without homebrew libomp installed.

With libomp installed `/opt/homebrew/opt/libomp/lib/libomp.dylib` exists.

**Comment by ankane** [comment]
Can you see if it works after running:

```sh
install_name_tool -change @@HOMEBREW_PREFIX@@/opt/libomp/lib/libomp.dylib /opt/homebrew/opt/libomp/lib/libomp.dylib /Users/tim/Downloads/lib_lightgbm.dylib
```

**Comment by timcraft** [comment]
Yep that works with libomp installed 👍

Without libomp installed:

    /Users/tim/.gem/ruby/3.0.0/gems/ffi-1.14.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/tim/Downloads/lib_lightgbm.dylib': dlopen(/Users/tim/Downloads/lib_lightgbm.dylib, 5): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib (LoadError)
      Referenced from: /Users/tim/Downloads/lib_lightgbm.dylib
      Reason: image not found

**Comment by ankane** [comment]
Great, just pushed a new release (0.2.3). Can you remove `LightGBM.ffi_lib = ...` and try it with and without OpenMP?

**Comment by timcraft** [comment]
Certainly. New release works as expected with libomp installed 🎉

Without libomp installed I get two backtraces:

    /Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.3/lib/lightgbm/ffi.rb:9:in `rescue in <module:FFI>': OpenMP not found. Run `brew install libomp` (LoadError)
    ...
    /Users/tim/.gem/ruby/3.0.0/gems/ffi-1.14.2/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'lib_lightgbm.arm64.dylib': dlopen(lib_lightgbm.arm64.dylib, 5): image not found. (LoadError)
    Could not open library 'lib_lightgbm.so': dlopen(lib_lightgbm.so, 5): image not found.
    Could not open library 'lib_lightgbm.so.dylib': dlopen(lib_lightgbm.so.dylib, 5): image not found.
    Could not open library '/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.3/vendor/lib_lightgbm.arm64.dylib': dlopen(/Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.3/vendor/lib_lightgbm.arm64.dylib, 5): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
      Referenced from: /Users/tim/.gem/ruby/3.0.0/gems/lightgbm-0.2.3/vendor/lib_lightgbm.arm64.dylib
      Reason: image not found
    ...

Thanks for your all your work on these great gems!

**Comment by ankane** [comment]
Great, looks like it's working (the second backtrace looks to be due to Ruby setting `cause` when exceptions are raised in a `rescue` block). Thanks for the help! Will apply this same approach to other ML gems.

**Comment by ankane** [comment]
Just fyi, was also able to cross-compile for Linux ARM ([code](https://github.com/ankane/ml-builds/blob/master/.github/workflows/lightgbm-linux-arm.yml)), so if you're ever using Docker on your machine and have some time to try it, there's a [build artifact here](https://github.com/ankane/ml-builds/actions/runs/637544155).

**Comment by timcraft** [comment]
Thanks, I don't use Docker so someone else will have to test that one out.
