### ISSUE TITLE
Missing feature_name method

### ISSUE THREAD

**Issue by jsuchal** [ankane/lightgbm#4]
We are using this library, but seems like when we load model from file we cannot access the feature names. 

In our setup we have a features repository that loads actual data for a model based on feature names, so we have to store the feature names elsewhere. However looking into https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Booster.html#lightgbm.Booster.feature_name and the saved model file, the feature names are already stored in the model, we are probably only missing a wrapper for native method.

I am not very familiar with FFI so if you have any pointers how to add this I am willing to do a PR on this.

Awesome work on this library wrapper so far!

**Comment by ankane** [comment]
Hey @jsuchal, thanks for reporting! Added in the commit above. This was very similar to the `feature_names` method for datasets, but the general approach for adding new methods is to find it in the [C API header](https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/c_api.h), attach it in `lib/lightgbm/ffi.rb`, and then add it to the Ruby class.

**Comment by StrikerRUS** [comment]
Hey @ankane ! Just want let you know that it is possible to not be limited with 255-length (or any other value) buffer size. It is possible to achieve by repeating the call of C API function in case of returned value in `out_buffer_len` was larger than `buffer_len`. Just the same as in `model_to_string()`
https://github.com/ankane/lightgbm/blob/ba58e984c5e6d80a9b0d9b8b9789abef0c3d2259/lib/lightgbm/booster.rb#L105-L108


Please refer to https://github.com/microsoft/LightGBM/pull/4293.

**Comment by ankane** [comment]
Thanks @StrikerRUS! Fixed in https://github.com/ankane/lightgbm/commit/b5b3e193d49818a2cf267f630fd0d4d981e04f07.
