### ISSUE TITLE
Using github version of gem in gemfile

### ISSUE THREAD

**Issue by jsuchal** [ankane/lightgbm#5]
Sorry for bumping this, but seems like if i try to use version from github using

```ruby
gem 'lightgbm', github: 'ankane/lightgbm'
```

I get 

```
LoadError (Could not open library 'lib_lightgbm.so': lib_lightgbm.so: cannot open shared object file: No such file or directory.)
```

Seems like the release process adds these library files to vendor folder, but when using it directly it does not work. Any hints how I can use this?

**Comment by ankane** [comment]
Hey @jsuchal, it's not ideal, but you'll need to fork the gem, download the shared libraries (`bundle exec rake vendor:all`), update `.gitignore` so they can be committed, and then commit them to the fork.

**Comment by jsuchal** [comment]
@ankane hmm, is there a reason why these files are not committed to this original repo?

**Comment by ankane** [comment]
The files are somewhat large, so prefer to keep them out of Git.

**Comment by jsuchal** [comment]
Understood, any ETA on a new release?
